name: my_meltano_project
version: '1.0'
profile: meltano
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: target
log-path: logs
modules-path: dbt_modules
clean-targets:
- target
- dbt_modules
- logs
models:
  my_meltano_project:
      staging:
          +materialized: table
          +schema: staging