# This file is managed by the 'dbt' file bundle and updated automatically when `meltano upgrade` is run.
# To prevent any manual changes from being overwritten, remove the file bundle from `meltano.yml` or disable automatic updates:
#     meltano config --plugin-type=files dbt set _update transform/profile/profiles.yml false

config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: postgres
  outputs:
    postgres:
      type: postgres
      threads: 2
      host: "{{ env_var('db_host') }}"
      port: "{{ env_var('db_port') }}"
      user: "{{ env_var('db_user') }}"
      pass: "{{ env_var('db_password') }}"
      dbname: "{{ env_var('db_name') }}"
      schema: "{{ env_var('db_schema') }}"


